[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
request = { workspace = true }
url = { workspace = true }
response = { workspace = true }
request_url = { workspace = true }
global_type = { workspace = true }
utils = { workspace = true }